logging:
  version: 1
  disable_existing_loggers: false
  app_name: "CorpusCollector"

  formatters:
    standard:
      class: logging.Formatter
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: standard
      stream: ext://sys.stdout

    file:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: standard
      filename: debugging_logs.txt
      maxBytes: 10485760
      backupCount: 5
      encoding: utf8

  root:
    level: INFO
    handlers: [ console, file ]

  loggers:
    app_logger:
      level: INFO
      handlers: [ console, file ]
      propagate: false

    app_debugger:
      level: WARNING
      handlers: [ console, file ]
      propagate: false
